---
title: "Feb_27_2018"
author: "Kazu"
date: "2/26/2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
library(ISLR);library(leaps)
```
# Chapter 6 Lab 2: Ridge Regression and the Lasso
```{r}
dim(Hitters)
sum(is.na(Hitters$Salary))
Hitters=na.omit(Hitters)
dim(Hitters)
sum(is.na(Hitters))

x=model.matrix(Salary~.,Hitters)[,-1]
y=Hitters$Salary
# note: "The model.matrix() function is particularly useful for creating x; not only does it produce a matrix corresponding to the 19 predictors but it also automatically transforms any qualitative variables into dummy variables. The latter property is important because glmnet() can only take numerical, quantitative inputs."
# Ridge Regression
library(glmnet)
grid=10^seq(10,-2,length=100)
ridge.mod=glmnet(x,y,alpha=0,lambda=grid)
dim(coef(ridge.mod))
ridge.mod$lambda[50]
coef(ridge.mod)[,50]
sqrt(sum(coef(ridge.mod)[-1,50]^2))
ridge.mod$lambda[60]
coef(ridge.mod)[,60]
sqrt(sum(coef(ridge.mod)[-1,60]^2))
predict(ridge.mod,s=50,type="coefficients")[1:20,]
set.seed(1)
train=sample(1:nrow(x), nrow(x)/2)
test=(-train)
y.test=y[test]
## Next we fit a ridge regression model on the training set, and evaluate its MSE on the test set, using λ = 4. Note the use of the predict() function again. This time we get predictions for a test set, by replacing type="coefficients" with the newx argument.
ridge.mod=glmnet(x[train,],y[train],alpha=0,lambda=grid, thresh=1e-12)
ridge.pred=predict(ridge.mod,s=4,newx=x[test,])
mean((ridge.pred-y.test)^2) # MSE 101036.8
## The test MSE is 101037. Note that if we had instead simply fit a model with just an intercept, we would have predicted each test observation using the mean of the training observations. In that case, we could compute the test set MSE like this:
mean((mean(y[train])-y.test)^2) 
# We could also get the same result by fitting a ridge regression model with a very large value of λ. Note that 1e10 means 1010.
ridge.pred=predict(ridge.mod,s=1e10,newx=x[test,])
mean((ridge.pred-y.test)^2) # 193253.1
# So fitting a ridge regression model with λ = 4 leads to a much lower test MSE than fitting a model with just an intercept. We now check whether there is any benefit to performing ridge regression with λ = 4 instead of just performing least squares regression. Recall that least squares is simply ridge regression with λ = 0.7
ridge.pred=predict(ridge.mod,s=0,newx=x[test,],exact=T)
mean((ridge.pred-y.test)^2)
lm(y~x, subset=train)
predict(ridge.mod,s=0,exact=T,type="coefficients")[1:20,]
# In general, if we want to fit a (unpenalized) least squares model, then we should use the lm() function, since that function provides more useful outputs, such as standard errors and p-values for the coefficients. In general, instead of arbitrarily choosing λ = 4, it would be better to use cross-validation to choose the tuning parameter λ. We can do this using the built-in cross-validation function, cv.glmnet(). By default, the function performs ten-fold cross-validation, though this can be changed using the argument nfolds. Note that we set a random seed first so our results will be reproducible, since the choice of the cross-validation folds is random.
set.seed(1)
cv.out=cv.glmnet(x[train,],y[train],alpha=0)
plot(cv.out)
bestlam=cv.out$lambda.min
bestlam # 212
# Therefore, we see that the value of λ that results in the smallest cross- validation error is 212. What is the test MSE associated with this value of λ?
ridge.pred=predict(ridge.mod,s=bestlam,newx=x[test,])
mean((ridge.pred-y.test)^2)
# This represents a further improvement over the test MSE that we got using λ = 4. Finally, we refit our ridge regression model on the full data set, using the value of λ chosen by cross-validation, and examine the coefficient estimates.
out=glmnet(x,y,alpha=0)
predict(out,type="coefficients",s=bestlam)[1:20,]
```
# 6.6.2 Lasso
```{r}
# We saw that ridge regression with a wise choice of λ can outperform least squares as well as the null model on the Hitters data set. We now ask whether the lasso can yield either a more accurate or a more interpretable model than ridge regression. In order to fit a lasso model, we once again use the glmnet() function; however, this time we use the argument alpha=1. Other than that change, we proceed just as we did in fitting a ridge model.
lasso.mod=glmnet(x[train,],y[train],alpha=1,lambda=grid)
plot(lasso.mod)
# We can see from the coefficient plot that depending on the choice of tuning parameter, some of the coefficients will be exactly equal to zero. We now perform cross-validation and compute the associated test error.

set.seed(1)
cv.out=cv.glmnet(x[train,],y[train],alpha=1) # 
plot(cv.out)
bestlam=cv.out$lambda.min
lasso.pred=predict(lasso.mod,s=bestlam,newx=x[test,])
mean((lasso.pred-y.test)^2) # 100743.4
# This is substantially lower than the test set MSE of the null model and of least squares, and very similar to the test MSE of ridge regression with λ chosen by cross-validation. However, the lasso has a substantial advantage over ridge regression in that the resulting coefficient estimates are sparse. Here we see that 12 of the 19 coefficient estimates are exactly zero. So the lasso model with λ chosen by cross-validation contains only seven variables.
out=glmnet(x,y,alpha=1,lambda=grid)
lasso.coef=predict(out,type="coefficients",s=bestlam)[1:20,]
lasso.coef
lasso.coef[lasso.coef!=0]
```
# practice
```{r}
# 2 a, b, (and c if possible)

# 5 c, d (at least for Min Yao)
##  It is well-known that ridge regression tends to give similar coefficient values to correlated variables, whereas the lasso may give quite different coefficient values to correlated variables. We will now explore this property in a very simple setting. Suppose that n = 2, p = 2, x11 = x12, x21 = x22. Furthermore, suppose that y1+y2 =0 and x11+x21 =0 and x12+x22 =0,so that the estimate for the intercept in a least squares, ridge regression, or lasso model is zero: βˆ0 = 0.
## (a) Write out the ridge regression optimization problem in this setting
## (KN) see my notebook.
## (b) Argue that in this setting, the ridge coefficient estimates satisfy βˆ 1 = βˆ 2 .
## (KN) no clear to me
## (c) Write out the lasso optimization problem in this setting.
## (KN) see my notebook. Just replace lamda part
## (d) Argue that in this setting, the lasso coefficients βˆ1 and βˆ2 are not unique—in other words, there are many possible solutions to the optimization problem in (c). Describe these solutions.
## (KN) ?
```

# 8 (you already did this for best subset; update for lasso)
```{r}
# (a) Use the rnorm() function to generate a predictor X of length n = 100, as well as a noise vector ε of length n = 100.
rm(x,y)
set.seed(1);x<-rnorm(n=100);eps<-rnorm(n=100)
# (b) Generate a response vector Y of length n = 100 according to the model
#b0<-2;b1<-3;b2<- -1;b3<- 0.5 # set1
b0<-5;b1<-6;b2<- 7;b3<- 8 # Geoff's set
y<-b0 + b1 * x + b2 * x^2 +b3*x^3 + eps
# (c) Use the regsubsets() function to perform best subset selection in order to choose the best model containing the predictors X, X2, . . . , X10. What is the best model obtained according to Cp, BIC, and adjusted R2? Show some plots to provide evidence for your answer, and report the coefficients of the best model ob- tained. Note you will need to use the data.frame() function to create a single data set containing both X and Y .
library(leaps)
data<-data.frame(X=x, Y=y)
system.time(regfit.full<-regsubsets(Y~X+I(X^2)+I(X^3)+I(X^4)+I(X^5)+I(X^6)+I(X^7)+I(X^8)+I(X^9)+I(X^10), data=data,nvmax=10))

reg.full.summary <- summary(regfit.full)
#par(mfrow = c(2, 2)) # preventing errorsin plot
# Cp
plot(reg.full.summary$cp, xlab = "Number of variables", ylab = "C_p", type = "l")
points(which.min(reg.full.summary$cp), reg.full.summary$cp[which.min(reg.full.summary$cp)], col = "red", cex = 2, pch = 20)
# bic
plot(regfit.full,scale="bic")
plot(reg.full.summary$bic, xlab = "Number of variables", ylab = "BIC", type = "l")
points(which.min(reg.full.summary$bic), reg.full.summary$bic[which.min(reg.full.summary$bic)], col = "red", cex = 2, pch = 20)
# Adjusted R^2
plot(reg.full.summary$adjr2, xlab = "Number of variables", ylab = "Adjusted R^2", type = "l")
points(which.max(reg.full.summary$adjr2), reg.full.summary$adjr2[which.max(reg.full.summary$adjr2)], col = "red", cex = 2, pch = 20)

## (d) Repeat (c), using forward stepwise selection and also using back- wards stepwise selection. How does your answer compare to the results in (c)?
regfit.fwd<-regsubsets(Y~X+I(X^2)+I(X^3)+I(X^4)+I(X^5)+I(X^6)+I(X^7)+I(X^8)+I(X^9)+I(X^10), data=data,nvmax=10,method="forward")
# alternative description (learned from Geoff'sscript)
regfit.fwd2 <- regsubsets(y ~ poly(x, 10, raw=T), data = data, nvmax = 10, method = "forward")

regfit.bwd<-regsubsets(Y~X+I(X^2)+I(X^3)+I(X^4)+I(X^5)+I(X^6)+I(X^7)+I(X^8)+I(X^9)+I(X^10), data=data,nvmax=10,method="backward")
coef(regfit.full,7)
coef(regfit.fwd,7)
coef(regfit.bwd,7)

# (e) Now fit a lasso model to the simulated data, again using X,X2, . . . , X 10 as predictors. Use cross-validation to select the optimal value of λ. Create plots of the cross-validation error as a function of λ. Report the resulting coefficient estimates, and discuss the results obtained.
library(glmnet)
# lasso.mod=glmnet(x[train,],y[train],alpha=1,lambda=grid) # text way
data.full <- data.frame(y = y, x = x)
xmat <- model.matrix(y ~ x + I(x^2) + I(x^3) + I(x^4) + I(x^5) + I(x^6) + I(x^7) + I(x^8) + I(x^9) + I(x^10), data = data.full)[, -1] # 
# how about 
# xmat2<-model.matrix(y~.,data=data.full) # this is not correct. Geoff's data set itself has x^2, X^3, ...x^10.
system.time(cv.lasso <- cv.glmnet(xmat, y, alpha = 1));plot(cv.lasso)
#cv.lasso2 <- cv.glmnet(xmat2, y, alpha = 1);plot(cv.lasso2)
bestlam<-cv.lasso$lambda.min # the best lamda

lasso<-glmnet(xmat,y,alpha=1) # there seems two ways to use glmnet?
# one described in text and another using model.matrix?
# textbook described "grid" method, but glmnet automatically spits out bestlam
predict(lasso, s = bestlam, type = "coefficients")[1:11, ]
predict(cv.lasso, s ="lambda.min", type = "coefficients")[1:11, ] # same! not necessary to get "lasso". use cv.lasso
coef(cv.lasso, s = "lambda.min") # same! 
# regfit.full etc (best subset selectio) is more precise.

# (f) Now generate a response vector Y according to the model Y = β0 + β7X7 + ε, and perform best subset selection and the lasso. Discuss the results obtained.
b0<-5;b7<-2 # Geoff's parameter
set.seed(1);x<-rnorm(n=100,mean=10,sd=1);eps<-rnorm(n=100,1,0.1)
data2<-data.frame(x=x,y=b0+b7*(x^7)+eps)
# 
regfit.full<-regsubsets(y ~ poly(x, 10, raw=T), data = data2, nvmax = 10) # error
regfit.full<-regsubsets(y ~ poly(x, 9, raw=T), data = data2, nvmax = 9)
regfit.fwd<-regsubsets(y ~ poly(x, 9, raw=T), data = data2, nvmax = 9,method="forward")
regfit.bwd<-regsubsets(y ~ poly(x, 9, raw=T), data = data2, nvmax = 9,method="backward")
xmat.ex9 <- model.matrix(y ~ poly(x, 10, raw=T), data = data2)[, -1] # 
# summary for regfit.full
reg.summary <- summary(regfit.full)
#par(mfrow = c(2, 2))
plot(reg.summary$cp, xlab = "Number of variables", ylab = "C_p", type = "l")
points(which.min(reg.summary$cp), reg.summary$cp[which.min(reg.summary$cp)], col = "red", cex = 2, pch = 20)
plot(reg.summary$bic, xlab = "Number of variables", ylab = "BIC", type = "l")
points(which.min(reg.summary$bic), reg.summary$bic[which.min(reg.summary$bic)], col = "red", cex = 2, pch = 20)
plot(reg.summary$adjr2, xlab = "Number of variables", ylab = "Adjusted R^2", type = "l")
points(which.max(reg.summary$adjr2), reg.summary$adjr2[which.max(reg.summary$adjr2)], col = "red", cex = 2, pch = 20)
# coeff
coef(regfit.full,9)
coef(regfit.fwd,9)
coef(regfit.bwd,9)
coef(cv.glmnet(xmat.ex9, data2$y, alpha = 1),10)[1:10]
plot(data2$x,data2$y)
cv.out<-cv.glmnet(xmat.ex9, data2$y, alpha = 1)
predict(glmnet(xmat.ex9, data2$y, alpha = 1),newx=xmat.ex9[1:5,],s= cv.out$lambda.min)
data2[1:5,]
# 
plot(regfit.full, scale="Cp")
plot(regfit.full, scale="bic")
plot(regfit.full, scale="adjr2")
#
plot(cv.glmnet(xmat.ex9, data2$y, alpha = 1)) # lambda.min is 500735.2
plot(glmnet(xmat.ex9, data2$y, alpha = 1),xvar = "lambda", label = TRUE)
```
# 9 d
# 9 In this exercise, we will predict the number of applications received using the other variables in the College data set.
```{r}
# (a) Split the data set into a training set and a test set.
set.seed(1)
summary(College)
#x=model.matrix(Apps~.,College)[,-1] # Remove the first column, (Intercept)
x=model.matrix(Apps~.,College) # Does not remove the first column, (Intercept)
y=College$Apps
dim(x) # 777 17
set.seed(1)
train=sample(c(TRUE,FALSE), nrow(College),rep=TRUE)
test=(!train)
# train=sample(1:nrow(x), nrow(x)/2) # divide into two. glmnet vignet way
# test=(-train) # interesting way found in glmet vignet?
x.test=x[test,]
# x.train=x[train,]
y.test=y[test]
# y.train=y[train]
# (b) Fit a linear model using least squares on the training set, and report the test error obtained.
colnames(College)
sum(is.na(College)) # no NA
# use regsubsets()
regfit.best<-regsubsets(Apps~.,data=College[train,],nvmax=17)
summary(regfit.best)
plot(regfit.best)
#
val.errors=rep(NA,17)
for(i in 1:17){
   coefi=coef(regfit.best,id=i)
   pred=x.test[,names(coefi)]%*%coefi
   val.errors[i]=mean((College$Apps[test]-pred)^2)
}
val.errors
which.min(val.errors) # 5
# MSE. There is no predict function for this
#mean((predict(summary(rigfit.full),newx=x.test)-y.test)^2)
coef(regfit.best,5)
# from text book
predict.regsubsets=function(object,newdata,id,...){
  form=as.formula(object$call[[2]])
  mat=model.matrix(form,newdata)
  coefi=coef(object,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi
}
as.formula(regfit.best$call[[2]])
coef(regfit.best,id=5)

predict.regsubsets.test<-predict.regsubsets(regfit.best,newdata=College[test,],id=5)
length(predict.regsubsets.test) # 377
#
lm.train<-lm(Apps~., data=College,subset=train)
summary(lm.train)
pred.lm<-predict(lm.train,newdata=College[test,-2]) # does not work
length(pred.lm) # 400
dim(College[test,])
library(reshape2)
melt.data<-melt(cbind(data.frame(pred.lm=pred.lm,pred.regsubsets=predict.regsubsets.test),Apps=College[test,2]),id="Apps")
str(melt.data)
library(ggplot2)
ggplot(melt.data,aes(x=Apps,y=value,colour=variable,alpha=0.1)) + geom_point()
# MSE 
mean((pred.lm - College[test,"Apps"])^2) # 1520331 for lm
mean((predict.regsubsets.test - College[test,"Apps"])^2) # 1492114 for regsubsets
  

# (c) Fit a ridge regression model on the training set, with λ chosen by cross-validation. Report the test error obtained
library(glmnet)

#ridge.mod=glmnet(x,y,alpha=0,lambda=grid) # If alpha=0 then a ridge regression model is fit, and if alpha=1 then a lasso model is fit. 
# Recall from Chapter 3 that the least squares fitting procedure estimates β0,β1,...,βp using the values that minimize: RSS (residual sum of squares, Fig3.1, p62)
ridge.ex9=glmnet(College[train,-2],College[train,"Apps"],alpha=0) # error
ridge.ex9=glmnet(x[train,-1],College[train,"Apps"],alpha=0) # removing intercept in x
cv.ridge.ex9<-cv.glmnet(x[train,-1],College[train,"Apps"],alpha=0)
predict(cv.ridge.ex9,s=cv.ridge.ex9$lambda.min,exact=T,type="coefficients")[1:18,] # coefficients
ridge.predict.ex9<-predict(cv.ridge.ex9,s=cv.ridge.ex9$lambda.min,newx=x[test,-1])
# MSE
mean((ridge.predict.ex9 - College[test,"Apps"])^2) # 2585067

# (d) Fit a lasso model on the training set, with λ chosen by cross- validation. Report the test error obtained, along with the number of non-zero coefficient estimates.
lasso.ex9=glmnet(x[train,-1],College[train,"Apps"],alpha=1) # removing intercept in x
cv.lasso.ex9<-cv.glmnet(x[train,-1],College[train,"Apps"],alpha=1)
lasso.ex9.coef<-predict(cv.lasso.ex9,s=cv.lasso.ex9$lambda.min,exact=T,type="coefficients")[1:18,] # coefficients
lasso.ex9.coef[!lasso.ex9.coef==0] #non zero
lasso.ex9.coef[lasso.ex9.coef!=0] #non zero. this is also OK.
lasso.predict.ex9<-predict(cv.lasso.ex9,s=cv.ridge.ex9$lambda.min,newx=x[test,-1])
# MSE
mean((lasso.predict.ex9 - College[test,"Apps"])^2) # 2010635. smaller than ridge
```
# 11 a,b,c, for all but PCR; we will add that next week.
```{r}
# We will now try to predict per capita crime rate in the Boston data set.
# (a) Try out some of the regression methods explored in this chapter, such as best subset selection, the lasso, ridge regression, and PCR. Present and discuss results for the approaches that you consider.
# (b) Propose a model (or set of models) that seem to perform well on this data set, and justify your answer. Make sure that you are evaluating model performance using validation set error, cross- validation, or some other reasonable alternative, as opposed to using training error.
# (c) Does your chosen model involve all of the features in the data set? Why or why not?
```
