---
title: "March27_2018_KN"
author: "Kazu"
date: "3/26/2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ISLR);library(splines)
attach(Wage)

```
# 7.8.3 GAMs
```{r}
# GAMs
gam1=lm(wage~ns(year,4)+ns(age,5)+education,data=Wage)
library(gam)
gam.m3=gam(wage~s(year,4)+s(age,5)+education,data=Wage)
par(mfrow=c(1,3))
plot(gam.m3, se=TRUE,col="blue")
# The generic plot() function recognizes that gam.m3 is an object of class gam, and invokes the appropriate plot.gam() method. Conveniently,even though plot.gam() gam1 is not of class gam but rather of class lm, we can still use plot.gam() on it. Figure 7.11 was produced using the following expression:
plot.gam(gam1, se=TRUE, col="red") 
gam.m1=gam(wage~s(age,5)+education,data=Wage)
gam.m2=gam(wage~year+s(age,5)+education,data=Wage)
anova(gam.m1,gam.m2,gam.m3,test="F")
summary(gam.m3)
preds=predict(gam.m2,newdata=Wage)
# We can also use local regression fits as building blocks in a GAM, using the lo() function
gam.lo=gam(wage~s(year,df=4)+lo(age,span=0.7)+education,data=Wage)
plot.gam(gam.lo, se=TRUE, col="green")
# Here we have used local regression for the age term, with a span of 0.7. We can also use the lo() function to create interactions before calling the gam() function. For example,
gam.lo.i=gam(wage~lo(year,age,span=0.5)+education,data=Wage)
library(akima)
plot(gam.lo.i)
# In order to fit a logistic regression GAM, we once again use the I() function in constructing the binary response variable, and set family=binomial.
gam.lr=gam(I(wage>250)~year+s(age,df=5)+education,family=binomial,data=Wage)
par(mfrow=c(1,3))
plot(gam.lr,se=T,col="green")
# It is easy to see that there are no high earners in the <HS category:
table(education,I(wage>250))
gam.lr.s=gam(I(wage>250)~year+s(age,df=5)+education,family=binomial,data=Wage,subset=(education!="1. < HS Grad"))
plot(gam.lr.s,se=T,col="green")
detach()
```
# practice
```{r}
# 7. The Wage data set contains a number of other features not explored in this chapter, such as marital status (maritl), job class (jobclass), and others. Explore the relationships between some of these other predictors and wage, and use non-linear fitting techniques in order to fit flexible models to the data. Create plots of the results obtained, and write a summary of your findings.
attach(Wage)
#?pairs
#pairs(Wage)
names(Wage)
library(ggplot2)
library(GGally) # from Min Yao repo
ggpairs(Wage)
# check individual predictor
ggplot(Wage,aes(as.factor(year),wage))+geom_violin() # no effects
ggplot(Wage,aes(maritl,wage))+geom_violin() # has effects
ggplot(Wage,aes(race,wage))+geom_violin() # has effects
ggplot(Wage,aes(education,wage))+geom_violin() # has strong effects
ggplot(Wage,aes(region,wage))+geom_violin() # only Middle Atlantic
ggplot(Wage,aes(jobclass,wage))+geom_violin() # has effects
ggplot(Wage,aes(health,wage))+geom_violin() # has effects
ggplot(Wage,aes(health_ins,wage))+geom_violin() # has strong effects
ggplot(Wage,aes(logwage,wage))+geom_point() # just transformation

# non-linear regression using poly() and estimate coefficient by ridge or lasso
# which degree I need to use?

# (3/27) GAM and slpline
library(splines);library(gam)
str(Wage)
# smoothing spline
gam.ex7.1=gam(wage~year+s(age ,5)+ maritl + race + education + jobclass + health_ins ,data=Wage)
gam.ex7.2=gam(wage~s(age,5)+ maritl + race + education + jobclass + health_ins ,data=Wage) # omit year
gam.ex7.3=gam(wage~year+ lo(age)+ maritl + race + education + jobclass + health_ins ,data=Wage) # change age into local regression

anova(gam.ex7.1,gam.ex7.2,gam.ex7.3) # having year is significant?
#pdf(file="gam.ex7.1.pdf")
par(mfrow=c(2,4))
plot.gam(gam.ex7.1, se=TRUE,col="blue")
summary(gam.ex7.1)
par(mfrow=c(2,3))
plot.gam(gam.ex7.2, se=TRUE,col="red")
summary(gam.ex7.2)

# how to plot predict?

detach()
```
# 8. Fit some of the non-linear models investigated in this chapter to the Auto data set. Is there evidence for non-linear relationships in this data set? Create some informative plots to justify your answer.

```{r}
Auto
pairs(Auto)
library(ggplot2) 
library(GGally) # from Min Yao repo
ggpairs(Auto[-9])

```
# 10 This question relates to the College data set.
```{r}
## (a) Split the data into a training set and a test set. Using out-of-state tuition as the response and the other variables as the predictors, perform forward stepwise selection on the training set in order to identify a satisfactory model that uses just a subset of the predictors.
summary(College)
## (b) Fit a GAM on the training data, using out-of-state tuition as the response and the features selected in the previous step as the predictors. Plot the results, and explain your findings.

## (c) Evaluate the model obtained on the test set, and explain the results obtained.

## (d) For which variables, if any, is there evidence of a non-linear relationship with the response?

```